### PR TITLE
Fix finding URL not respecting `--scm-base-url`

### LINKED ISSUE #190: URL in finding does not respect `--scm-base-url`
**Describe the bug**
When using `--scm-base-url`, the `URL` of a finding should reference that value. However, the domain appears to be hard-coded to `github.com`. 

**To Reproduce**
```sh
$ ./poutine analyze_org corp --scm-base-url="https://github.contoso.com/" --token="..."

Rule: If condition always evaluates to true
Severity: error
Description: GitHub Actions expressions used in if condition of jobs or steps
must not contain extra characters or spaces.
Otherwise, the condition is always true.
Documentation: https://boostsecurityio.github.io/poutine/rules/if_always_true

+-----------------------------+----------------------------------+-----------------------------------------------------------------------------------------------+
|         REPOSITORY          |             DETAILS              |                                              URL                                              |
+-----------------------------+----------------------------------+-----------------------------------------------------------------------------------------------+
| corp/repo1                  | .github/workflows/reviewdog.yaml | https://github.com/corp/repo1/tree/HEAD/.github/workflows/reviewdog.yaml#L51                  |
|                             | Job: run                         |                                                                                               |
|                             | Step: 2                          |                                                                                               |
|                             |                                  |                                                                                               |
+-----------------------------+----------------------------------+-----------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by rgmz**
This fixes #190.

Tested against an instance of GHES. It works for rules like "CI Runner Debug Enabled" and "Pull Request Runs on Self-Hosted GitHub Actions Runner" but not "GitHub Action from Unverified Creator used". That requires somehow passing the base domain to [`PurlFromGithubActions` and `PurlFromDockerImage`](https://github.com/boostsecurityio/poutine/blob/e259b09e5f955a241cb4510e8c188dbaa17292a7/models/purl.go#L62), which could be more complicated.

### CODE REVIEW

File: analyze/analyze.go [hunk 1]
```diff
@@ -274,7 +275,16 @@ func (a *Analyzer) generatePackageInsights(ctx context.Context, tempDir string,
 		return nil, fmt.Errorf("failed to get commit SHA: %w", err)
 	}
 
-	purl, _ := models.NewPurl(fmt.Sprintf("pkg:%s/%s", repo.GetProviderName(), repo.GetRepoIdentifier()))
+	var (
+		purl   models.Purl
+		domain = a.ScmClient.GetProviderBaseURL()
+	)
+	if domain != scm_domain.DefaultGitHubDomain && domain != scm_domain.DefaultGitLabDomain {
+		purl, _ = models.NewPurl(fmt.Sprintf("pkg:%s/%s?repository_url=%s", repo.GetProviderName(), repo.GetRepoIdentifier(), domain))
```
Comment (rgmz) [inline analyze/analyze.go:283]: I _think_ it's fine that `repository_url` is the domain without schema. Some purl examples include schema, others don't.

https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst

File: providers/scm/domain/scm_domain.go [hunk 2]
```diff
@@ -1,10 +1,13 @@
-package scm
+package scm_domain
```
Comment (rgmz) [inline providers/scm/domain/scm_domain.go:1]: One possible solution to prevent cyclical references.

**Review by SUSTAPLE117 — APPROVED** [review]
